command: ["sh", "-c", "python -m backend.manage seed && exec uvicorn backend.main:app"]
env:
  - name: DB_AUTH_MODE
    value: oauth
    
  - name: VAPID_PRIVATE_KEY
    value: "p3JcPr0SNrTjd7l7NM5abdKf9CgC_z0smfNDUlEXdro"

  - name: VAPID_CONTACT
    value: "mailto:nimeshraja18@gmail.com"


